sudo: false # route your build to the container-based infrastructure for a faster build

language: ruby

rvm:
  - 2.6.3

cache: bundler # caching bundler gem packages will speed up build

before_install: gem update bundler

install:
  - bundle install

before_script:
  - chmod +x script/cibuild # or do this locally and commit

script:
  - "script/cibuild"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
