sudo: required
language: ruby
rvm:
  - 2.6.3
cache:
  bundler: true
install:
  - bundle config set deployment 'true'
  - echo 'Installing Bundle packages!'
  - bundle install
run:
  - bundle exec jekyll serve --watch

